# version: "3.9"
services:
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=change_me_32_random_chars

  backend:
    build: ./backend
    ports: ["8000:8000"]
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/voicecbt
      - CLICKHOUSE_URL=http://clickhouse:8123/default
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./backend:/app
    depends_on: [db, clickhouse]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]

  clickhouse:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    ports: ["8123:8123", "9000:9000"]